In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [96]:
import pandas as pd

url = "/content/drive/MyDrive/ProyectoFin/cardio_train.csv"
df = pd.read_csv(url, sep=";")

df.info()

df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

np.int64(0)

In [97]:
df_temp = df

In [101]:
df[df["cardio"] == 0]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
5,8,21914,1,151,67.0,120,80,2,2,0,0,0,0
6,9,22113,1,157,93.0,130,80,3,1,0,0,1,0
8,13,17668,1,158,71.0,110,70,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69987,99979,18852,1,151,49.0,120,80,1,1,0,0,1,0
69988,99981,21978,1,160,59.0,110,70,1,1,0,0,1,0
69991,99988,20609,1,159,72.0,130,90,2,2,0,0,1,0
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [93]:
temp_df[(temp_df["ap_hi"] > 250) & (temp_df["ap_hi"] < 40)]

Empty DataFrame
Columns: [id, age, gender, height, weight, ap_hi, ap_lo, cholesterol, gluc, smoke, alco, active, cardio, imc]
Index: []

In [60]:
dfl[dfl['weight'] <35]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
3752,5306,15400,1,120,30.0,110,70,1,1,0,0,1,0
14722,21040,22663,1,143,34.0,100,70,1,1,0,0,1,0
16906,24167,17272,2,170,31.0,150,90,2,2,0,0,1,1
18559,26503,18140,1,160,30.0,120,80,1,1,0,0,1,1
22016,31439,15359,1,146,32.0,100,70,1,1,0,0,0,0
26806,38312,23284,1,157,23.0,110,80,1,1,0,0,1,0
29488,42156,20408,2,177,22.0,120,80,1,1,1,1,1,0
33511,47872,21081,1,153,34.0,110,70,3,3,0,0,1,1
33817,48318,21582,2,178,11.0,130,90,1,1,0,0,1,1
34276,48976,14664,2,128,28.0,120,80,1,1,0,0,1,0
35314,50443,19802,1,146,32.0,130,80,1,2,0,0,0,0
38417,54851,21809,1,154,32.0,110,60,1,1,0,0,1,0
41905,59853,21334,1,143,30.0,103,61,2,1,0,0,1,0
48080,68667,19255,1,143,33.0,100,60,1,1,0,0,1,0
51837,73914,19817,2,139,34.0,120,70,1,1,0,0,1,0
55852,79686,23370,1,152,34.0,140,90,1,1,0,0,1,1
60188,85931,21855,1,162,21.0,120,80,2,1,0,0,1,1
60699,86650,18875,1,171,29.0,110,70,2,1,0,0,1,1

In [68]:
temp_df = dfl

In [70]:
temp_df = temp_df[(temp_df["weight"] <= 200) & (temp_df["weight"] >= 35)]
temp_df = temp_df[(temp_df["height"] <= 220) & (temp_df["height"] >= 120)]

In [71]:
temp_df.shape

(68650, 13)

In [73]:
temp_df[(temp_df["weight"] > 200) & (temp_df["weight"] < 35)]

Empty DataFrame
Columns: [id, age, gender, height, weight, ap_hi, ap_lo, cholesterol, gluc, smoke, alco, active, cardio]
Index: []

In [66]:
temp_df[(temp_df["height"] <= 200) & (temp_df["height"] >= 35)]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [67]:
temp_df[(temp_df["height"] > 200) & (temp_df["height"] < 35)]

Empty DataFrame
Columns: [id, age, gender, height, weight, ap_hi, ap_lo, cholesterol, gluc, smoke, alco, active, cardio]
Index: []

In [63]:
dfl[dfl['weight'] >150]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
389,552,16718,2,165,169.0,120,80,1,1,0,0,1,0
435,618,16765,1,186,200.0,130,70,1,1,0,0,0,0
2441,3438,19171,2,177,177.0,130,90,1,1,0,0,1,1
2458,3470,23646,2,159,165.0,130,70,1,1,0,0,0,0
3413,4825,14585,1,159,159.0,100,80,1,1,0,0,1,0
4743,6716,17218,2,176,180.0,140,90,1,1,0,0,1,1
6003,8526,14441,1,172,166.0,140,90,1,1,0,0,1,1
6153,8757,20990,1,122,161.0,120,80,1,1,0,0,1,1
7636,10899,15937,2,183,154.0,160,120,1,1,1,0,1,1
8171,11662,17646,2,97,170.0,160,100,1,1,1,0,1,1
8423,12020,14697,1,170,165.0,120,80,1,1,0,0,1,0
12435,17757,22077,1,137,161.0,150,100,2,1,0,0,0,1
12770,18218,19594,1,75,168.0,120,80,1,1,1,0,1,1
14520,20750,22031,1,170,165.0,120,80,1,1,0,0,1,0
14675,20970,21135,1,159,153.0,120,80,1,1,0,0,1,1
15366,21958,17405,1,125,167.0,180,90,1,2,0,0,1,1
15690,22413,19604,2,182,156.0,160,100,1,1,0,0,1,1
16384,23402,18026,2,170,156.0,150,90,1,3,0,0,0,0
18031,25757,15086,2,190,165.0,160,60,1,1,0,0,0,1
18641,26619,14680,2,178,152.0,140,90,2,2,0,0,1,0
18648,26630,18273,1,168,168.0,110,70,1,1,0,0,1,1
18952,27063,15421,1,155,163.0,180,100,1,1,0,0,1,1
19579,27962,23193,1,162,162.0,150,90,1,1,0,0,1,1
20028,28605,19777,1,112,167.0,180,120,1,1,0,1,1,0
20092,28683,20656,2,165,178.0,120,80,1,1,1,1,1,0
21593,30845,20430,1,168,166.0,150,90,3,3,0,0,1,1
23913,34186,19074,1,81,156.0,140,90,1,1,0,0,1,0
25021,35738,18991,1,174,158.0,140,90,2,2,1,0,1,0
27384,39156,15292,1,80,178.0,140,90,3,3,0,0,1,1
29069,41534,14729,2,180,164.0,120,80,2,3,0,0,1,0
34595,49413,15505,2,174,165.0,120,90,1,2,0,1,1,0
35030,50043,23394,1,170,152.0,200,140,1,3,0,0,1,1
40712,58175,21728,1,154,162.0,120,80,1,1,0,0,1,0
41844,59768,20464,1,164,164.0,140,90,3,3,0,0,1,1
42445,60631,19450,1,160,155.0,120,80,1,1,0,0,1,1
45358,64802,19834,1,104,159.0,200,100,3,1,0,0,0,1
45378,64829,17418,2,190,180.0,140,80,2,2,0,0,1,1
46573,66494,20453,1,160,158.0,150,90,1,1,0,0,1,1
49188,70222,19623,2,174,168.0,125,90,2,1,0,1,1,0
50413,71945,15117,2,180,200.0,150,90,1,1,0,0,1,1
51009,72770,22012,1,170,152.0,220,120,3,1,0,0,0,0
54778,78159,22566,2,177,160.0,170,110,3,3,0,0,1,1
56177,80152,15526,2,170,171.0,120,80,1,1,0,0,1,1
56426,80523,21392,1,164,160.0,130,90,2,2,0,0,1,1
58488,83462,14530,2,178,170.0,150,105,1,1,1,0,1,1
58808,83932,21924,1,170,170.0,120,80,1,1,0,0,1,1
59625,85128,17643,1,104,165.0,120,80,1,1,0,0,1,0
60592,86506,18975,2,180,180.0,140,100,3,1,0,0,1,1
61285,87498,20939,2,180,183.0,110,80,3,3,0,1,1,1
61362,87612,16615,2,196,180.0,130,80,3,1,0,0,1,1
61788,88220,18956,2,165,178.0,120,80,1,1,0,0,1,0
63687,90930,23483,1,154,155.0,170,80,2,1,0,0,1,0
63937,91284,21115,1,164,164.0,120,80,1,1,0,0,1,0
64661,92301,21705,1,169,172.0,120,70,2,1,0,0,1,0
65005,92778,21076,1,176,154.0,140,80,1,1,0,0,1,1
69109,98709,19077,2,175,155.0,110,100,1,1,0,0,1,1

In [74]:
temp_df["imc"] = temp_df["weight"] / ((temp_df["height"] / 100) ** 2)

In [81]:
temp_df = temp_df[(temp_df["height"] <= 220) & (temp_df["height"] >= 130)]

In [85]:
temp_df[temp_df['imc']>55]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,imc
338,474,21078,1,157,142.0,120,80,1,1,0,0,1,1,57.608828
389,552,16718,2,165,169.0,120,80,1,1,0,0,1,0,62.075298
435,618,16765,1,186,200.0,130,70,1,1,0,0,0,0,57.810151
1598,2258,16109,1,160,150.0,120,80,2,1,0,0,1,1,58.593750
2340,3298,20988,1,160,150.0,160,75,1,1,0,0,1,1,58.593750
2441,3438,19171,2,177,177.0,130,90,1,1,0,0,1,1,56.497175
2458,3470,23646,2,159,165.0,130,70,1,1,0,0,0,0,65.266406
3413,4825,14585,1,159,159.0,100,80,1,1,0,0,1,0,62.893082
4732,6703,19868,1,164,149.0,120,80,2,2,0,0,1,1,55.398572
4743,6716,17218,2,176,180.0,140,90,1,1,0,0,1,1,58.109504
6003,8526,14441,1,172,166.0,140,90,1,1,0,0,1,1,56.111412
6052,8600,16058,2,159,150.0,200,130,1,1,0,0,1,1,59.333096
8423,12020,14697,1,170,165.0,120,80,1,1,0,0,1,0,57.093426
11393,16293,18232,1,155,135.0,130,90,3,3,0,0,0,1,56.191467
12435,17757,22077,1,137,161.0,150,100,2,1,0,0,0,1,85.779743
14520,20750,22031,1,170,165.0,120,80,1,1,0,0,1,0,57.093426
14675,20970,21135,1,159,153.0,120,80,1,1,0,0,1,1,60.519758
15319,21895,23460,1,146,120.0,130,80,2,1,0,0,1,0,56.295740
16974,24257,18235,1,160,150.0,140,90,2,1,0,0,1,1,58.593750
18648,26630,18273,1,168,168.0,110,70,1,1,0,0,1,1,59.523810
18952,27063,15421,1,155,163.0,180,100,1,1,0,0,1,1,67.845994
19579,27962,23193,1,162,162.0,150,90,1,1,0,0,1,1,61.728395
20092,28683,20656,2,165,178.0,120,80,1,1,1,1,1,0,65.381084
21593,30845,20430,1,168,166.0,150,90,3,3,0,0,1,1,58.815193
23129,33032,18766,1,153,136.0,140,90,2,1,0,0,1,0,58.097313
26204,37425,19695,1,158,139.0,150,100,1,1,0,0,1,1,55.680179
28448,40679,19707,1,142,117.0,130,90,1,1,0,0,1,0,58.024202
30309,43344,18989,1,164,150.0,130,90,1,1,0,0,1,1,55.770375
31375,44788,19616,1,156,137.0,120,80,1,1,0,0,1,0,56.295201
34005,48586,15855,1,163,150.0,120,80,1,1,0,0,1,1,56.456773
36865,52682,19738,1,162,150.0,130,80,1,1,0,0,0,1,57.155921
38808,55405,17419,1,159,142.0,200,100,1,1,0,0,1,1,56.168664
40712,58175,21728,1,154,162.0,120,80,1,1,0,0,1,0,68.308315
41507,59303,15896,1,152,128.0,120,80,1,1,0,0,1,0,55.401662
41844,59768,20464,1,164,164.0,140,90,3,3,0,0,1,1,60.975610
42445,60631,19450,1,160,155.0,120,80,1,1,0,0,1,1,60.546875
46303,66134,21399,1,162,148.0,140,80,3,2,0,0,1,1,56.393842
46573,66494,20453,1,160,158.0,150,90,1,1,0,0,1,1,61.718750
49188,70222,19623,2,174,168.0,125,90,2,1,0,1,1,0,55.489497
49377,70504,23211,2,144,120.0,130,80,1,1,0,0,1,0,57.870370
50413,71945,15117,2,180,200.0,150,90,1,1,0,0,1,1,61.728395
51909,74028,23228,1,142,129.0,140,90,1,3,0,0,1,1,63.975402
56177,80152,15526,2,170,171.0,120,80,1,1,0,0,1,1,59.169550
56426,80523,21392,1,164,160.0,130,90,2,2,0,0,1,1,59.488400
58808,83932,21924,1,170,170.0,120,80,1,1,0,0,1,1,58.823529
60160,85894,20238,1,161,145.0,150,100,1,1,0,0,1,0,55.939200
60592,86506,18975,2,180,180.0,140,100,3,1,0,0,1,1,55.555556
61285,87498,20939,2,180,183.0,110,80,3,3,0,1,1,1,56.481481
61788,88220,18956,2,165,178.0,120,80,1,1,0,0,1,0,65.381084
63687,90930,23483,1,154,155.0,170,80,2,1,0,0,1,0,65.356721
63937,91284,21115,1,164,164.0,120,80,1,1,0,0,1,0,60.975610
64661,92301,21705,1,169,172.0,120,70,2,1,0,0,1,0,60.221981
65418,93381,18242,1,165,150.0,175,100,3,3,0,0,1,1,55.096419
67866,96921,21763,1,133,123.0,180,100,2,1,0,0,1,1,69.534739
69708,99562,21357,1,144,115.0,140,90,1,1,0,1,0,1,55.459105

In [86]:
temp_df[temp_df['imc']<12]

Empty DataFrame
Columns: [id, age, gender, height, weight, ap_hi, ap_lo, cholesterol, gluc, smoke, alco, active, cardio, imc]
Index: []

In [78]:
print(temp_df["imc"].shape)

(68650,)

In [ ]:
temp_df[(temp_df["weight"] <= 200) & (temp_df["weight"] >= 35)]